inputDir: ./test
outputDir: ./test_proc
outputColor: rgb
steps:
  - name: equalize
    color: red
  - name: filter
    color: red
    filter:
      - -1 0 1
      - -1 0 1
      - -1 0 1
    strategy: linear
    border: ignore
