inputDir: ./train
outputDir: ./train_proc
outputColor: rgb | red | green | blue | gray
steps:
  - name: equalize
    color: rgb | red | green | blue | gray
  - name: quantize
    color: rgb | red | green | blue | gray
    delta: 16
    technique: uniform | mean | median
  - name: filter
    color: rgb | red | green | blue | gray
    filter:
      - -1 0 1
      - -1 0 1
      - -1 0 1
    strategy: linear | mean | median
    border: ignore | crop | pad | extend
  - name: gaussiannoise
    color: rgb | red | green | blue | gray
    rate: 0.30
    mean: null
    stddev: null
  - name: saltnpeppernoise
    color: rgb | red | green | blue | gray
    rate: 0.30
