inputDir: ./train
outputDir: ./train_proc
outputColor: rgb
steps:
  - name: equalize
    color: rgb
  - name: quantize
    color: rgb
    delta: 16
    technique: uniform
  - name: filter
    color: rgb
    filter:
      - -1 0 1
      - -1 0 1
      - -1 0 1
    strategy: linear
    border: ignore
  - name: gaussiannoise
    color: rgb
    rate: 0.30
    mean: null
    stddev: null
  - name: saltnpeppernoise
    color: rgb
    rate: 0.30
